// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.24.3
// source: vitalSignPublish.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VoidRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VoidRequest) Reset() {
	*x = VoidRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vitalSignPublish_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VoidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VoidRequest) ProtoMessage() {}

func (x *VoidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_vitalSignPublish_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VoidRequest.ProtoReflect.Descriptor instead.
func (*VoidRequest) Descriptor() ([]byte, []int) {
	return file_vitalSignPublish_proto_rawDescGZIP(), []int{0}
}

type RPN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hospital string `protobuf:"bytes,2,opt,name=hospital,proto3" json:"hospital,omitempty"`
}

func (x *RPN) Reset() {
	*x = RPN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vitalSignPublish_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPN) ProtoMessage() {}

func (x *RPN) ProtoReflect() protoreflect.Message {
	mi := &file_vitalSignPublish_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPN.ProtoReflect.Descriptor instead.
func (*RPN) Descriptor() ([]byte, []int) {
	return file_vitalSignPublish_proto_rawDescGZIP(), []int{1}
}

func (x *RPN) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RPN) GetHospital() string {
	if x != nil {
		return x.Hospital
	}
	return ""
}

type RPNs struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rpns []*RPN `protobuf:"bytes,1,rep,name=rpns,proto3" json:"rpns,omitempty"`
}

func (x *RPNs) Reset() {
	*x = RPNs{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vitalSignPublish_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPNs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPNs) ProtoMessage() {}

func (x *RPNs) ProtoReflect() protoreflect.Message {
	mi := &file_vitalSignPublish_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPNs.ProtoReflect.Descriptor instead.
func (*RPNs) Descriptor() ([]byte, []int) {
	return file_vitalSignPublish_proto_rawDescGZIP(), []int{2}
}

func (x *RPNs) GetRpns() []*RPN {
	if x != nil {
		return x.Rpns
	}
	return nil
}

type Patient struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Hospital string `protobuf:"bytes,2,opt,name=hospital,proto3" json:"hospital,omitempty"`
}

func (x *Patient) Reset() {
	*x = Patient{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vitalSignPublish_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patient) ProtoMessage() {}

func (x *Patient) ProtoReflect() protoreflect.Message {
	mi := &file_vitalSignPublish_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patient.ProtoReflect.Descriptor instead.
func (*Patient) Descriptor() ([]byte, []int) {
	return file_vitalSignPublish_proto_rawDescGZIP(), []int{3}
}

func (x *Patient) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Patient) GetHospital() string {
	if x != nil {
		return x.Hospital
	}
	return ""
}

type Patients struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Patients []*Patient `protobuf:"bytes,1,rep,name=patients,proto3" json:"patients,omitempty"`
}

func (x *Patients) Reset() {
	*x = Patients{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vitalSignPublish_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Patients) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Patients) ProtoMessage() {}

func (x *Patients) ProtoReflect() protoreflect.Message {
	mi := &file_vitalSignPublish_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Patients.ProtoReflect.Descriptor instead.
func (*Patients) Descriptor() ([]byte, []int) {
	return file_vitalSignPublish_proto_rawDescGZIP(), []int{4}
}

func (x *Patients) GetPatients() []*Patient {
	if x != nil {
		return x.Patients
	}
	return nil
}

type Msg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status bool   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Topic  string `protobuf:"bytes,2,opt,name=topic,proto3" json:"topic,omitempty"`
	Msg    string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Msg) Reset() {
	*x = Msg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_vitalSignPublish_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Msg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Msg) ProtoMessage() {}

func (x *Msg) ProtoReflect() protoreflect.Message {
	mi := &file_vitalSignPublish_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Msg.ProtoReflect.Descriptor instead.
func (*Msg) Descriptor() ([]byte, []int) {
	return file_vitalSignPublish_proto_rawDescGZIP(), []int{5}
}

func (x *Msg) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

func (x *Msg) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *Msg) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_vitalSignPublish_proto protoreflect.FileDescriptor

var file_vitalSignPublish_proto_rawDesc = []byte{
	0x0a, 0x16, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73,
	0x69, 0x67, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x22, 0x0d, 0x0a, 0x0b, 0x56, 0x6f,
	0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x31, 0x0a, 0x03, 0x52, 0x50, 0x4e,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x22, 0x31, 0x0a, 0x04,
	0x52, 0x50, 0x4e, 0x73, 0x12, 0x29, 0x0a, 0x04, 0x72, 0x70, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x15, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x52, 0x50, 0x4e, 0x52, 0x04, 0x72, 0x70, 0x6e, 0x73, 0x22,
	0x35, 0x0a, 0x07, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f,
	0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x70, 0x69, 0x74, 0x61, 0x6c, 0x22, 0x41, 0x0a, 0x08, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x35, 0x0a, 0x08, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52,
	0x08, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x22, 0x45, 0x0a, 0x03, 0x4d, 0x73, 0x67,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x70, 0x69,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x70, 0x69, 0x63, 0x12, 0x10,
	0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x32, 0xaa, 0x03, 0x0a, 0x10, 0x56, 0x69, 0x74, 0x61, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x50, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x12, 0x42, 0x0a, 0x09, 0x63, 0x68, 0x65, 0x63, 0x6b, 0x52, 0x50,
	0x4e, 0x73, 0x12, 0x1d, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x56, 0x6f, 0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x16, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70, 0x75, 0x62,
	0x6c, 0x69, 0x73, 0x68, 0x2e, 0x52, 0x50, 0x4e, 0x73, 0x12, 0x4a, 0x0a, 0x0d, 0x63, 0x68, 0x65,
	0x63, 0x6b, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x1d, 0x2e, 0x76, 0x69, 0x74,
	0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x56, 0x6f,
	0x69, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x76, 0x69, 0x74, 0x61,
	0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x3b, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65,
	0x72, 0x52, 0x50, 0x4e, 0x12, 0x15, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x52, 0x50, 0x4e, 0x1a, 0x15, 0x2e, 0x76, 0x69,
	0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x4d,
	0x73, 0x67, 0x12, 0x3d, 0x0a, 0x0d, 0x75, 0x6e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72,
	0x52, 0x50, 0x4e, 0x12, 0x15, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x52, 0x50, 0x4e, 0x1a, 0x15, 0x2e, 0x76, 0x69, 0x74,
	0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x4d, 0x73,
	0x67, 0x12, 0x43, 0x0a, 0x0f, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x1a,
	0x15, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69,
	0x73, 0x68, 0x2e, 0x4d, 0x73, 0x67, 0x12, 0x45, 0x0a, 0x11, 0x75, 0x6e, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x2e, 0x76, 0x69,
	0x74, 0x61, 0x6c, 0x73, 0x69, 0x67, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x1a, 0x15, 0x2e, 0x76, 0x69, 0x74, 0x61, 0x6c, 0x73, 0x69,
	0x67, 0x6e, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x73, 0x68, 0x2e, 0x4d, 0x73, 0x67, 0x42, 0x0a, 0x5a,
	0x08, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_vitalSignPublish_proto_rawDescOnce sync.Once
	file_vitalSignPublish_proto_rawDescData = file_vitalSignPublish_proto_rawDesc
)

func file_vitalSignPublish_proto_rawDescGZIP() []byte {
	file_vitalSignPublish_proto_rawDescOnce.Do(func() {
		file_vitalSignPublish_proto_rawDescData = protoimpl.X.CompressGZIP(file_vitalSignPublish_proto_rawDescData)
	})
	return file_vitalSignPublish_proto_rawDescData
}

var file_vitalSignPublish_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_vitalSignPublish_proto_goTypes = []interface{}{
	(*VoidRequest)(nil), // 0: vitalsignpublish.VoidRequest
	(*RPN)(nil),         // 1: vitalsignpublish.RPN
	(*RPNs)(nil),        // 2: vitalsignpublish.RPNs
	(*Patient)(nil),     // 3: vitalsignpublish.Patient
	(*Patients)(nil),    // 4: vitalsignpublish.Patients
	(*Msg)(nil),         // 5: vitalsignpublish.Msg
}
var file_vitalSignPublish_proto_depIdxs = []int32{
	1, // 0: vitalsignpublish.RPNs.rpns:type_name -> vitalsignpublish.RPN
	3, // 1: vitalsignpublish.Patients.patients:type_name -> vitalsignpublish.Patient
	0, // 2: vitalsignpublish.VitalSignPublish.checkRPNs:input_type -> vitalsignpublish.VoidRequest
	0, // 3: vitalsignpublish.VitalSignPublish.checkPatients:input_type -> vitalsignpublish.VoidRequest
	1, // 4: vitalsignpublish.VitalSignPublish.registerRPN:input_type -> vitalsignpublish.RPN
	1, // 5: vitalsignpublish.VitalSignPublish.unregisterRPN:input_type -> vitalsignpublish.RPN
	3, // 6: vitalsignpublish.VitalSignPublish.registerPatient:input_type -> vitalsignpublish.Patient
	3, // 7: vitalsignpublish.VitalSignPublish.unregisterPatient:input_type -> vitalsignpublish.Patient
	2, // 8: vitalsignpublish.VitalSignPublish.checkRPNs:output_type -> vitalsignpublish.RPNs
	4, // 9: vitalsignpublish.VitalSignPublish.checkPatients:output_type -> vitalsignpublish.Patients
	5, // 10: vitalsignpublish.VitalSignPublish.registerRPN:output_type -> vitalsignpublish.Msg
	5, // 11: vitalsignpublish.VitalSignPublish.unregisterRPN:output_type -> vitalsignpublish.Msg
	5, // 12: vitalsignpublish.VitalSignPublish.registerPatient:output_type -> vitalsignpublish.Msg
	5, // 13: vitalsignpublish.VitalSignPublish.unregisterPatient:output_type -> vitalsignpublish.Msg
	8, // [8:14] is the sub-list for method output_type
	2, // [2:8] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_vitalSignPublish_proto_init() }
func file_vitalSignPublish_proto_init() {
	if File_vitalSignPublish_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_vitalSignPublish_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VoidRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vitalSignPublish_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vitalSignPublish_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPNs); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vitalSignPublish_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patient); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vitalSignPublish_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Patients); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_vitalSignPublish_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Msg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_vitalSignPublish_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vitalSignPublish_proto_goTypes,
		DependencyIndexes: file_vitalSignPublish_proto_depIdxs,
		MessageInfos:      file_vitalSignPublish_proto_msgTypes,
	}.Build()
	File_vitalSignPublish_proto = out.File
	file_vitalSignPublish_proto_rawDesc = nil
	file_vitalSignPublish_proto_goTypes = nil
	file_vitalSignPublish_proto_depIdxs = nil
}
